export const adminDepartmentsSortableColumns = [
  'id',
  'name',
  'identityNumber',
  'codeName',
  'addedAt',
  'editedAt',
  'removedAt',
  'addedUsername',
  'editedUsername',
  'removedUsername',
  'countryName',
  'cityName',
  'districtName',
  'organizationName',
  'zone',
  'direction',
  'establishmentedDate',
  'ranking',
  'electricPowerSource',
  'beverageSource',
  'beverageSourceNumber',
  'lengthResponsibleBorder',
  'lengthDryLand',
  'lengthWaterBoundaryLength',
  'distanceFromBorder',
  'distanceFromWestern',
  'distanceFromEastern',
  'distanceFromDetachment',
  'distanceFromDistrict',
  'networkMobicom',
  'networkSkytel',
  'networkUnitel',
  'networkGmobile',
  'networkVsat',
] as const;

export type AdminDepartmentsSortableColumn =
  (typeof adminDepartmentsSortableColumns)[number];
