export const adminOrganizationsSortableColumns = [
  'id',
  'name',
  'identityNumber',
  'codeName',
  'addedAt',
  'editedAt',
  'removedAt',
  'addedUsername',
  'editedUsername',
  'removedUsername',
  'countryName',
  'cityName',
  'districtName',
  'zone',
  'direction',
  'establishmentedDate',
  'pronunciation',
  'borderRepresentative',
  'ranking',
  'electricPowerSource',
  'lengthResponsibleBorder',
  'lengthDryLand',
  'lengthWaterBoundaryLength',
  'distanceFromBorder',
  'distanceFromWestern',
  'distanceFromEastern',
  'distanceFromWesternNeighborDetachment',
  'distanceFromEasternNeighborDetachment',
  'distanceFromUlaanbaatar',
  'distanceFromCity',
  'distanceFromDistrict',
  'networkMobicom',
  'networkSkytel',
  'networkUnitel',
  'networkGmobile',
  'nerelberM100k',
  'coordinateM100k',
] as const;

export type AdminOrganizationsSortableColumn =
  (typeof adminOrganizationsSortableColumns)[number];
