import { CountryTableInsert } from '../schemas';
import { addedAt, toumkuId } from './vars';

export type CountrySeed = Omit<CountryTableInsert, 'id'> & { id: string };

export const countriesSeed: CountrySeed[] = [
  {
    id: 'c2b2478a-1449-464a-9ba9-b3dd9b707379',
    name: 'Австри',
    codeName: 'Бүгд Найрамдах Австри Улc',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'd9ea8886-f8fe-4186-bb77-3349c27e34bd',
    name: 'Азербайжан',
    codeName: 'Бүгд Найрамдах Азербайжан Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '7a413865-f6ec-4cd5-87a4-f2f7e3348f6f',
    name: 'Америкийн Нэгдсэн Улс ',
    codeName: 'Америкийн Нэгдсэн Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '7bbae35e-780d-4095-93a3-6239a069b9dd',
    name: 'Ангол',
    codeName: 'Бүгд Найрамдах Ангол Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '26913a08-c2d8-4ccf-855d-b59412a7e71d',
    name: 'Афганистан',
    codeName: 'Афганистан',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'f1379afc-a54e-43c6-b493-d944aace8ac0',
    name: 'Балба',
    codeName: 'Холбооны Бүгд Найрамдах Ардчилсан Балба Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '866758db-4d47-4170-a513-3e0d22d911b3',
    name: 'Бангладеш ',
    codeName: 'Бүгд Найрамдах Бангладеш Ард Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '4854ae01-e0a9-4623-9057-2e3fac6bc734',
    name: 'Барбадос',
    codeName: 'Барбадос',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'e93b5c6b-261a-4aef-88fa-c0b53537d2d3',
    name: 'Бахрейн ',
    codeName: 'Бахрейны Хаант Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'f541492c-f4d6-4b31-878a-6306479a8dde',
    name: 'Беларусь',
    codeName: 'Бүгд Найрамдах Беларусь Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '8517597a-6669-4587-9924-b76068bc82b5',
    name: 'Бельги ',
    codeName: 'Бельгийн Хаант Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'c758051a-feb9-4a8f-9926-53a92431d4a0',
    name: 'Бенин',
    codeName: 'Бүгд Найрамдах Бенин Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'b0f63102-c2cf-499d-b02d-da4dfa81ed6d',
    name: 'Болгар',
    codeName: 'Бүгд Найрамдах Болгар Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '50435bbe-129e-4b51-9f66-939fba838c09',
    name: 'Боливи',
    codeName: 'Боливийн Олон Үндэстний Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '16b227a4-35b9-4478-b638-f409734ddbbb',
    name: 'Босни ба Херцеговин',
    codeName: 'Босни ба Херцеговин',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '2fe2839f-54af-44ef-969f-0596efc6dc91',
    name: 'Ботсвана',
    codeName: 'Бүгд Найрамдах Ботсвана Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'de7fa32e-5b9e-45d9-ad07-d41fb855526a',
    name: 'Бруней',
    codeName: 'Бруней Даруссалам Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '227f2479-f6ed-4977-8ad9-8adef32bf067',
    name: 'Бурунди',
    codeName: 'Бүгд Найрамдах Бурунди Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'ce907464-6abd-4750-8a86-c4dcabe8ae45',
    name: 'Бутан',
    codeName: 'Бутаны Хаант Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '912146be-c186-47ed-8e4f-45d4b2eccfb8',
    name: 'Вануату',
    codeName: 'Бүгд Найрамдах Вануату Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'f6778114-3d97-4579-b7fb-da8f07f73e10',
    name: 'Ватикан',
    codeName: 'Ватикан Хот Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '0af98541-aac9-4c86-9d92-8bfc3e07a24e',
    name: 'Венесуэл',
    codeName: 'Боливарын Бүгд Найрамдах Венесуэл Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '8bfe4beb-031c-473e-8079-f5a05816935a',
    name: 'Вьетнам',
    codeName: 'Бүгд Найрамдах Социалист Вьетнам Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '413694d1-6f05-4fb5-9009-363c377514df',
    name: 'Габон',
    codeName: 'Бүгд Найрамдах Габон Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '433e4fe0-b8ad-4278-8668-6cf1f484b92d',
    name: 'Гамби',
    codeName: 'Бүгд Найрамдах Гамби Улс[15]',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '27a8b94f-9d1a-4b6d-8bea-39c3291dcba5',
    name: 'Гана',
    codeName: 'Бүгд Найрамдах Гана Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'cd71cea2-4bf6-4329-b8d8-f22d3bd686dc',
    name: 'Гватемал',
    codeName: 'Бүгд Найрамдах Гватемал Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '31dba84a-aa14-4909-a50d-787c41ee1204',
    name: 'Гвиней',
    codeName: 'Бүгд Найрамдах Гвиней Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'c7ab2104-ea4a-4abf-9c3b-0a82132b198c',
    name: 'Гвиней-Бисау ',
    codeName: 'Бүгд Найрамдах Гвиней-Бисау Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '8cdf2fd2-2581-4034-bedb-7ca86337346b',
    name: 'Грек',
    codeName: 'Бүгд Найрамдах Грек Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '8fa162d1-cbe9-43eb-9e9e-ee8496abb26c',
    name: 'Гүрж',
    codeName: 'Гүрж',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'bd424375-060e-451c-b698-9ebf1d1c598e',
    name: 'Дани',
    codeName: 'Данийн Хаант Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '999f57f7-a082-4698-8388-cf78ab74fd3c',
    name: 'Жибути',
    codeName: 'Бүгд Найрамдах Жибути Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '2a549931-e34e-4367-acbe-ac570b01127f',
    name: 'Замби',
    codeName: 'Бүгд Найрамдах Замби Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '907d83f4-84c3-4908-a041-b9c57c725a02',
    name: 'Зимбабве',
    codeName: 'Бүгд Найрамдах Зимбабве Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'e0a095af-7b1c-45e7-a6c6-92c95f390e43',
    name: 'Зүүн Тимор',
    codeName: 'Бүгд Найрамдах Ардчилсан Зүүн Тимор Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '84c6c1f8-0480-4651-994a-57625c21a0c1',
    name: 'Йемен',
    codeName: 'Бүгд Найрамдах Йемен Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'e9de8a5a-4534-4279-9e03-9835d16cf002',
    name: 'Иран',
    codeName: 'Исламын Бүгд Найрамдах Иран Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'e064e0cb-f6c2-4bdb-8025-9f3e0110f5ae',
    name: 'Испани',
    codeName: 'Испанийн Хаант Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '07af4460-e298-4a89-b5e8-bd0401352b3c',
    name: 'Итали',
    codeName: 'Бүгд Найрамдах Итали Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '444e498b-a65f-4273-9d48-3e9f8aa311be',
    name: 'Камбож',
    codeName: 'Камбожийн Хаант Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '306715c6-8592-418f-ac3f-86eaf6dce733',
    name: 'Канад',
    codeName: 'Канад',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'ff282ee4-bddf-476f-91fb-c110eaf758a1',
    name: 'Кени',
    codeName: 'Бүгд Найрамдах Кени Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '0705a5a8-a99f-4f73-a29c-000dddca84a1',
    name: 'Киргиз',
    codeName: 'Бүгд Найрамдах Киргиз Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '60a74eda-cb20-489d-826d-a9bfd705aa3c',
    name: 'Конго, Бүгд Найрамдах',
    codeName: 'Конго, Бүгд Найрамдах',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '20a286a1-e1e6-4cc7-957d-661255b59784',
    name: 'Косово ',
    codeName: 'Бүгд Найрамдах Косово Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '768c2ca9-175a-473f-824b-4e320c2391ed',
    name: 'Күүкийн арлууд',
    codeName: 'Күүкийн арлууд',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'fa4935fe-c9ac-41ee-b4ba-2f05324754e2',
    name: 'Ливи',
    codeName: 'Ливи Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'd6f500de-1c4c-41b0-adc6-2dc3c2f95513',
    name: 'Мавритани',
    codeName: 'Исламын Бүгд Найрамдах Мавритани Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '936893b2-9383-4267-82f7-d4b824ddfae6',
    name: 'Мальдив',
    codeName: 'Бүгд Найрамдах Мальдив Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '6cd98887-8504-4390-b497-27364d467e0a',
    name: 'Марокко',
    codeName: 'Мароккогийн Хаант Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'a49d4c36-1ff5-4c63-b003-04e3e2feb6a0',
    name: 'Мексик',
    codeName: 'Мексикийн Нэгдсэн Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '086274db-2212-444a-a040-1763802614b1',
    name: 'Монтенегро',
    codeName: 'Монтенегро',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'bccf45c0-0411-4527-b743-95fb3cf2016f',
    name: 'Мьянмар',
    codeName: 'Мьянмарын Холбооны Бүгд Найрамдах Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '0b15580f-6e02-425f-a436-9704e894b963',
    name: 'Нидерланд',
    codeName: 'Нидерландын хаант улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'a797023f-1097-47e6-bbf1-e8fb0d97f5c6',
    name: 'Ниуэ',
    codeName: 'Ниуэ',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '31070296-edf1-498a-bae0-ca91d7e90d90',
    name: 'Норвеги ',
    codeName: 'Норвегийн Хаант Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'f8bcd7f0-d56c-44b9-aa63-dfa613e74c59',
    name: 'Нэгдсэн Хаант Улс',
    codeName: 'Их Британи, Умард Ирландын Нэгдсэн Хаант Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '7d143dcc-526a-45d9-802d-716ed2e6764c',
    name: 'Орос',
    codeName: 'Оросын Холбооны Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'f7330a26-a0ed-4639-a30c-e85c1ab3b38d',
    name: 'Өмнөд Осети',
    codeName: 'Бүгд Найрамдах Өмнөд Осети Улс–Алани Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'bf4b5ed3-e516-4417-89b1-f5b960b2891c',
    name: 'Өмнөд Солонгос',
    codeName: 'Бүгд Найрамдах Солонгос Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '6eb69252-ae1a-4c90-8f10-d290d0ce1c6c',
    name: 'Өмнөд Судан',
    codeName: 'Бүгд Найрамдах Өмнөд Судан Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '9075b76c-d42e-4c5d-88a0-4f74fc6ec65d',
    name: 'Палестин',
    codeName: 'Палестин Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '0fa035f1-eca7-4bcc-91a0-c2a98d685e2f',
    name: 'Папуа Шинэ Гвиней',
    codeName: 'Папуа Шинэ Гвинейн Тусгаар Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'd751257d-b6ec-4311-a0af-cfe7601e42e8',
    name: 'Перу',
    codeName: 'Бүгд Найрамдах Перу Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '6dd8d863-84a5-48db-9952-4080ece8ca2a',
    name: 'Польш',
    codeName: 'Бүгд Найрамдах Польш Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '3ffa936d-4416-45ee-a2ca-c5e76d543871',
    name: 'Португал',
    codeName: 'Бүгд Найрамдах Португал Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '1048e8d2-b98a-4420-b8df-1c27eb4791b3',
    name: 'Руанда',
    codeName: 'Бүгд Найрамдах Руанда Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '06902c50-7bd5-45af-941e-d356c46adcce',
    name: 'Румын',
    codeName: 'Румын',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'b2f3914d-963c-4f97-81c6-92b1b1bc3a61',
    name: 'Самоа',
    codeName: 'Самоагийн Тусгаар Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'f38ca763-7789-4608-9d95-8a045e165eae',
    name: 'Сан-Марино',
    codeName: 'Бүгд Найрамдах Сан-Марино Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'dd68c5ba-2f65-4538-b80f-f4216e077fb4',
    name: 'Сент-Винсент ба Гренадин',
    codeName: 'Сент-Винсент ба Гренадин',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '243d3a2c-f86e-4dd9-84c4-b384926896c7',
    name: 'Сент-Китс ба Невис',
    codeName: 'Сент-Кристофер ба Невисийн Холбооны Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '97ed96cf-0495-415e-b942-8fd5db486b77',
    name: 'Серби',
    codeName: 'Бүгд Найрамдах Серби Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'bc01e080-6681-4e25-94cd-e65546568aca',
    name: 'Сири',
    codeName: 'Арабын Бүгд Найрамдах Сири Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'b3d79727-e422-4abd-a1f9-0612358db700',
    name: 'Словени',
    codeName: 'Бүгд Найрамдах Словени Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'fca3ff85-95fc-4f5e-a6a4-59ae767f96f5',
    name: 'Соломоны арлууд',
    codeName: 'Соломоны арлууд',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '9eb02ecc-d909-433f-91c3-1ac991e4e1e0',
    name: 'Сомали',
    codeName: 'Холбооны Бүгд Найрамдах Сомали Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'aec33a88-e524-4eca-8c77-835b18d52394',
    name: 'Судан',
    codeName: 'Бүгд Найрамдах Судан Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'dd2b72cb-512e-4d93-b3d9-a1af8815467a',
    name: 'Тажикистан',
    codeName: 'Бүгд Найрамдах Тажикистан Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'b0abcfe0-1b5a-4ba7-98c9-cd461c35d0d1',
    name: 'Тонга ',
    codeName: 'Тонгагийн Хаант Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '54059ffe-cdc8-4826-939f-2c5d3a0656ab',
    name: 'Төв Африкийн Бүгд Найрамдах Улс',
    codeName: 'Төв Африкийн Бүгд Найрамдах Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '5ee8e6a7-32a6-49f4-9587-7ff57c369ec3',
    name: 'Тунис',
    codeName: 'Бүгд Найрамдах Тунис Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '0968d9d0-e871-4c5d-9edd-ab7834a2a5d5',
    name: 'Туркменистан',
    codeName: 'Туркменистан',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'ef2f6b0f-55ef-43ef-9fde-51a3bea510a4',
    name: 'Уганда ',
    codeName: 'Бүгд Найрамдах Уганда Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '1064beba-6bbb-481e-b8cf-144f80134ba8',
    name: 'Узбекистан ',
    codeName: 'Бүгд Найрамдах Узбекистан Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '5af1897a-c9c0-46d5-a428-5e1010979e37',
    name: 'Украин',
    codeName: 'Украин',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'ee13a1c1-ba63-4d3a-af71-c64270d30567',
    name: 'Умард Македон ',
    codeName: 'Бүгд Найрамдах Умард Македон Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '8c205285-787b-4a4b-a8bb-6884370539e8',
    name: 'Унгар',
    codeName: 'Унгар',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'af3b7262-94a3-4179-8b50-d4957b9c6822',
    name: 'Уругвай',
    codeName: 'Дорнын Бүгд Найрамдах Уругвай Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '5966e83b-cb4e-415c-88f7-39b35748b1c1',
    name: 'Фижи ',
    codeName: 'Бүгд Найрамдах Фижи Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '0cfcaa54-c724-46c7-834f-5874019f55a5',
    name: 'Филиппин ',
    codeName: 'Бүгд Найрамдах Филиппин Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '9defec01-03ff-47c1-a30a-8a38c9358d84',
    name: 'Хаити',
    codeName: 'Бүгд Найрамдах Хаити Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '5a48c879-a24d-4d84-b538-3ef6d695d0c0',
    name: 'Чад ',
    codeName: 'Бүгд Найрамдах Чад Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '825dd7e5-9949-411e-9476-aac9f0ef4240',
    name: 'Чех',
    codeName: 'Бүгд Найрамдах Чех Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '2b54cc9c-3846-4a89-b6d0-72202741b2a8',
    name: 'Швейцар',
    codeName: 'Швейцарын Холбооны Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '0cf8b1a0-aa0f-46ca-8ec6-9cb28c171cf7',
    name: 'Шри Ланка',
    codeName: 'Бүгд Найрамдах Ардчилсан Социалист Шри Ланка Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '67ffaad2-e83e-4bf9-99fa-1df690690a37',
    name: 'Эквадор',
    codeName: 'Бүгд Найрамдах Эквадор Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'a35c01d2-dae4-4a32-b9ce-5533f8a3a87f',
    name: 'Эстони ',
    codeName: 'Бүгд Найрамдах Эстони Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '6adf4e94-8487-4a6a-bb0e-ea3ca4e86d03',
    name: 'Абхаз',
    codeName: 'Бүгд Найрамдах Абхаз Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '28eb177e-9f70-4651-9109-96b9c6838b75',
    name: 'Австрали ',
    codeName: 'Австралийн Хамтын Нөхөрлөлийн Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '71cf45ed-7e5c-410b-bb3b-6a72171e5651',
    name: 'Алжир',
    codeName: 'Бүгд Найрамдах Ардчилсан Алжир Ард Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'd63b3438-a5de-45fc-b07b-fd5f7677e3a7',
    name: 'Бахам',
    codeName: 'Бахамын Хамтын Нөхөрлөлийн Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '72e561a6-022b-46dc-8df5-be96b667af93',
    name: 'Белиз',
    codeName: 'Белиз',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '299a2034-af38-4f9f-b348-e29580ff7998',
    name: 'Бразил',
    codeName: 'Холбооны Бүгд Найрамдах Бразил Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '5cc3f520-790b-4acb-9ec9-76588a7bd7fd',
    name: 'Буркина Фасо',
    codeName: 'Буркина Фасо',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '6cdbb0b8-c8ff-4a0c-8b64-73596b9a6d2f',
    name: 'Бүгд Найрамдах Ардчилсан Сахарын Араб Улс',
    codeName: 'Бүгд Найрамдах Ардчилсан Сахарын Араб Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '0d424fed-0fc2-4079-9895-f2ca1533ea26',
    name: 'Гайана',
    codeName: 'Хамтын ажиллагааны Бүгд Найрамдах Гайана Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '94cddc2a-2eda-45e5-96b9-33d582b07674',
    name: 'Герман',
    codeName: 'Холбооны Бүгд Найрамдах Герман Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'f78423cd-2ec7-4abc-bce4-6f8d4eef1cac',
    name: 'Гренада',
    codeName: 'Гренада',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '0af75fa5-7f79-45c3-a91c-a2755e25032e',
    name: 'Доминика',
    codeName: 'Доминикийн Хамтын Нөхөрлөлийн Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '94f3b24d-4e9c-4fe5-8ecf-940f22e5a680',
    name: 'Доминиканы Бүгд Найрамдах Улс',
    codeName: 'Доминиканы Бүгд Найрамдах Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '2c35c5eb-2800-4a0f-922c-cbc3dec5b516',
    name: 'Египет',
    codeName: 'Арабын Бүгд Найрамдах Египет Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'ccb3fb8b-b01d-4851-9b79-0cfae01c4656',
    name: 'Израил',
    codeName: 'Израил Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '9f263c3c-436d-442f-8793-b467ea60235b',
    name: 'Индонез',
    codeName: 'Бүгд Найрамдах Индонез Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '7cc2f570-6e88-4ec0-875b-fd12357002cf',
    name: 'Йордан',
    codeName: 'Йорданы Хашимитын Хаант Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'fa1a6ff2-a1e9-4db7-b0f6-7c0e235e3f5a',
    name: 'Ирак',
    codeName: 'Бүгд Найрамдах Ирак Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'ef83d278-61cf-4fd1-9ffb-b4beb9e7bd8e',
    name: 'Ирланд',
    codeName: 'Ирланд',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '988f2bdd-e8a4-4f31-b546-4ec6c5f6d4ad',
    name: 'Исланд',
    codeName: 'Бүгд Найрамдах Исланд Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '04317f9c-a3b7-4d3b-968f-25d51089ecf1',
    name: 'Кабо-Верде',
    codeName: 'Бүгд Найрамдах Кабо-Верде Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '18f8c4a1-2a0d-4374-975e-86bc6ff07457',
    name: 'Казахстан',
    codeName: 'Бүгд Найрамдах Казахстан Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '49847339-3732-4ae9-802b-620f967bd114',
    name: 'Камерун',
    codeName: 'Бүгд Найрамдах Камерун Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'a8296655-25f6-4473-98c3-3cef2786bb6d',
    name: 'Катар',
    codeName: 'Катар Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '4888cc6a-70b0-4610-ab86-eb7ce38e8c4f',
    name: 'Кипр',
    codeName: 'Бүгд Найрамдах Кипр Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'd35e8c7b-be8b-4f34-9946-c2484f6993a7',
    name: 'Кирибати',
    codeName: 'Бүгд Найрамдах Кирибати Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '4de2e6b4-7967-4dbc-a0e2-c30c3acdcb39',
    name: 'Колумби',
    codeName: 'Бүгд Найрамдах Колумби Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '5e3c90a5-bcd1-4548-b741-a8443644e806',
    name: 'Коморос',
    codeName: 'Коморосын Холбооны Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '575393ce-2c35-4996-9626-f75f9b079c5c',
    name: 'Конго, Бүгд Найрамдах Ардчилсан',
    codeName: 'Конго, Бүгд Найрамдах Ардчилсан',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '981c0333-9386-45ab-8d69-9f3f690a5195',
    name: 'Коста-Рика',
    codeName: 'Бүгд Найрамдах Коста Рика Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'dc325f3e-18a1-4566-90ce-091fc9dbd7a5',
    name: "Кот-д'Ивуар",
    codeName: "Бүгд Найрамдах Кот-д'Ивуар Улс",
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'e4ef3e81-6425-4f38-908b-2f0515d4b86c',
    name: 'Куба',
    codeName: 'Бүгд Найрамдах Куба Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '27da72a0-335c-49b6-9254-e9792f1af3cf',
    name: 'Кувейт',
    codeName: 'Кувейт Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '6a454937-b9ed-41b6-a34a-701427bdf158',
    name: 'Лаос',
    codeName: 'Бүгд Найрамдах Ардчилсан Лаос Ард Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '2a82d319-6ef4-4ce8-adfa-58ac7e83f2ca',
    name: 'Латви',
    codeName: 'Бүгд Найрамдах Латви Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '9c52c9f4-7ad0-402c-960c-f83c6600cc9f',
    name: 'Лесото',
    codeName: 'Лесотогийн Хаант Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '18f8f8f6-0ede-4a69-9151-6e219c582673',
    name: 'Либери',
    codeName: 'Бүгд Найрамдах Либери Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '8c8ac196-e430-46f9-8a4f-aafedcff5ef5',
    name: 'Ливан',
    codeName: 'Бүгд Найрамдах Ливан Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '8bf0c842-3978-423d-aeb2-f55931a03821',
    name: 'Литва',
    codeName: 'Бүгд Найрамдах Литва Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '54e6ace9-da7f-4598-a507-fefbf7cc45aa',
    name: 'Лихтенштайн',
    codeName: 'Лихтенштайны Вант Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '837ed048-dd00-43c9-af23-c4c4e77859d0',
    name: 'Люксембург',
    codeName: 'Люксембургийн Их Гүнт Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '9c690321-2a2d-4bec-ae3f-5096f2d22efa',
    name: 'Маврики',
    codeName: 'Бүгд Найрамдах Маврики Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '61fea03f-4d4f-4649-b142-6dfcc009650e',
    name: 'Мадагаскар',
    codeName: 'Бүгд Найрамдах Мадагаскар Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'd3369ea6-028e-4a6c-bfa8-727f50d75c7f',
    name: 'Малави',
    codeName: 'Бүгд Найрамдах Малави Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'c241afe3-5ae0-4669-9cd3-c7f6d0ff6d05',
    name: 'Малайз ',
    codeName: 'Малайз ',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '4ca6eb44-8891-47b0-be88-5204f4497482',
    name: 'Мали',
    codeName: 'Бүгд Найрамдах Мали Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'b94b645c-ca62-47a0-af55-a208fa2b096e',
    name: 'Мальта',
    codeName: 'Бүгд Найрамдах Мальта Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'c101f4ab-53a7-4f78-a819-fb885e76fa11',
    name: 'Маршаллын арлууд',
    codeName: 'Маршаллын Арлуудын Бүгд Найрамдах Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'e85d0254-0646-4fce-8137-c1269498f74c',
    name: 'Микронези',
    codeName: 'Микронезийн Холбооны Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '577b8b59-a4c3-4c1e-8153-c2d85302fe47',
    name: 'Мозамбик',
    codeName: 'Бүгд Найрамдах Мозамбик Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '769b480f-6ff1-434b-8e90-e1284f497f17',
    name: 'Молдав',
    codeName: 'Бүгд Найрамдах Молдова Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'd471c79d-1557-40af-a6a2-32c2adc9d4d8',
    name: 'Монако',
    codeName: 'Монакогийн Гүнт Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'ee27b63c-0662-4f56-b93e-1d07407656e0',
    name: 'Монгол',
    codeName: 'Монгол',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '72110b07-e606-4c44-97a9-01b27035a88c',
    name: 'Намиби',
    codeName: 'Бүгд Найрамдах Намиби Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'c66ae8fe-be24-4d8d-91a7-8424a0d53a82',
    name: 'Науру',
    codeName: 'Бүгд Найрамдах Науру Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '908bcd00-ab18-4d01-8e6f-bddd39aa4833',
    name: 'Нигери',
    codeName: 'Холбооны Бүгд Найрамдах Нигери Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'a84b0f77-433d-464d-beeb-5090a27ca5c2',
    name: 'Нижер',
    codeName: 'Бүгд Найрамдах Нижер Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '2a02419b-b2c8-495e-9470-bcfbdc87bffe',
    name: 'Никарагуа',
    codeName: 'Бүгд Найрамдах Никарагуа Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '661d42e1-cdf8-4769-bc65-d1574b47b2b6',
    name: 'Оман',
    codeName: 'Оманы Султант Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'cfebb9c7-e9d0-43a8-bec6-c95220e08840',
    name: 'Өмнөд Африк',
    codeName: 'Өмнөд Африкийн Бүгд Найрамдах Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'd29fdc10-4302-4d23-a642-c6de661dba26',
    name: 'Пакистан',
    codeName: 'Исламын Бүгд Найрамдах Пакистан Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'bd486ec7-826c-47fd-8e24-4c6ab309956a',
    name: 'Палау',
    codeName: 'Бүгд Найрамдах Палау Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '1cf5c2a7-ca2d-4c7a-98dc-849ed6bc9b6a',
    name: 'ПанамУлс',
    codeName: 'Бүгд Найрамдах Панам Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '04b451a7-fbb1-47b4-8611-7f4b1a856dc4',
    name: 'Парагвай',
    codeName: 'Бүгд Найрамдах Парагвай Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'd45c4269-917a-4869-87d8-d439f271cb31',
    name: 'Приднестр',
    codeName: '᠌᠌Приднестрийн Бүгд Найрамдах Молдав Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '5e83b00d-bf8c-4f75-be16-0a1750d26466',
    name: 'Сальвадор',
    codeName: 'Бүгд Найрамдах Эль Сальвадор Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '699ecc51-009d-4db0-89c2-9910d523392c',
    name: 'Сан-Томе ба Принсипи',
    codeName: 'Бүгд Найрамдах Ардчилсан Сан-Томе ба Принсипи Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'fce52c62-781b-4953-aba3-9f24274e18d5',
    name: 'Саудын Араб',
    codeName: 'Саудын Арабын Хаант Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '54592119-4868-406a-b673-0d9d9332d01e',
    name: 'Сейшелийн арлууд',
    codeName: 'Сейшелийн Арлуудын Бүгд Найрамдах Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '10fe934e-1e68-4fa9-8237-a95cc559c1d6',
    name: 'Сенегал',
    codeName: 'Бүгд Найрамдах Сенегал Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'a1e637b3-f373-43e9-a844-47190e8655d3',
    name: 'Сент-Люси',
    codeName: 'Сент-Люси',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '7b99d93c-8250-4553-9590-3afd14413cfb',
    name: 'Сингапур',
    codeName: 'Бүгд Найрамдах Сингапур Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '28bc288c-62d0-4d2a-8760-b3cd4c877a92',
    name: 'Словак',
    codeName: 'Бүгд Найрамдах Словак Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '2725f3fa-ba43-47ae-92e2-7d9d93a54f54',
    name: 'Сомалиланд',
    codeName: 'Бүгд Найрамдах Сомалиланд Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '31b61e0b-4ca0-4a16-85e0-25f09851c72d',
    name: 'Суринам',
    codeName: 'Бүгд Найрамдах Суринам Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '3816a337-4123-4060-8e6d-62786e7dd55a',
    name: 'Сьерра Леон',
    codeName: 'Бүгд Найрамдах Сьерра Леон Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'dacda15c-efe0-4bae-b01c-60931bafc4d2',
    name: 'Тайвань',
    codeName: 'Бүгд Найрамдах Хятад Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'c8842c2a-c386-4d28-858e-7bfd2976306d',
    name: 'Тайланд ',
    codeName: 'Тайландын Хаант Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'fe5ed95e-8354-4372-b19f-11c830d6ed85',
    name: 'Танзани',
    codeName: 'Бүгд Найрамдах Нэгдсэн Танзани Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '4b4f196c-4ca3-4656-8f88-dde170fea483',
    name: 'Того ',
    codeName: 'Бүгд Найрамдах Того Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '58253a5e-2c37-4238-b43e-d7fcde40a160',
    name: 'Тринидад ба Тобаго',
    codeName: 'Бүгд Найрамдах Тринидад ба Тобаго Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '90d13807-ee59-471a-ad9f-7e93f34054cd',
    name: 'Тувалу',
    codeName: 'Тувалу',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'c989a090-15d4-4b2a-ad4a-ed9e1e657271',
    name: 'Турк ',
    codeName: 'Бүгд Найрамдах Турк Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'f2ea1f38-e07c-47a3-857a-42dbd8b35fee',
    name: 'Умард Кипр',
    codeName: 'Умард Киприйн Бүгд Найрамдах Турк Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'ea43fc11-5b2f-4209-a316-dc015b8be2c1',
    name: 'Умард Солонгос',
    codeName: 'Бүгд Найрамдах Ардчилсан Солонгос Ард Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '9a42a078-c463-4617-86ae-156c192bddc8',
    name: 'Финланд',
    codeName: 'Бүгд Найрамдах Финланд Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '29cda7dd-4753-407e-8367-f0b781971199',
    name: 'Франц',
    codeName: 'Бүгд Найрамдах Франц Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'e6247ded-d68a-429a-9fcb-781a1c1e7b09',
    name: 'Хондурас',
    codeName: 'Бүгд Найрамдах Хондурас Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'ad34e4bd-aa0b-4f1e-9170-b279d7675372',
    name: 'Хорват',
    codeName: 'Бүгд Найрамдах Хорват Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'e6e0897d-3bcd-4e85-af8b-1e8f4172d1a0',
    name: 'Хятад',
    codeName: 'Бүгд Найрамдах Хятад Ард Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '96ffa7f8-294b-4df1-b026-5fb44bb11bc3',
    name: 'Чили',
    codeName: 'Бүгд Найрамдах Чили Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '0fb17007-5f34-4529-8f3e-6b72dfcef947',
    name: 'Швед ',
    codeName: 'Шведийн Хаант Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'a5b3c416-77b2-4fb5-b959-6c25aaa62b41',
    name: 'Шинэ Зеланд',
    codeName: 'Шинэ Зеланд',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '8fe41732-0c7b-44a4-9237-5a58b5de58c9',
    name: 'Экваторын Гвиней',
    codeName: 'Экваторын Гвинейн Бүгд Найрамдах Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'c6d0ea4b-76c3-4dea-9364-ec6ffc5fcafa',
    name: 'Энэтхэг ',
    codeName: 'Бүгд Найрамдах Энэтхэг Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '0e9384b3-cd44-47ec-b5f0-6460ad6c007b',
    name: 'Эритрей ',
    codeName: 'Эритрей Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'fbbd5b4c-40cb-47d6-a56a-873af4cfaa1e',
    name: 'Эсватини',
    codeName: 'Эсватинийн Хаант Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: 'd8978c80-73d0-4a13-a7af-4f64cb96f3d1',
    name: 'Этиоп',
    codeName: 'Холбооны Бүгд Найрамдах Ардчилсан Этиоп Улс',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '6b3383ee-b277-436f-abfe-043ea25a961a',
    name: 'Ямайка',
    codeName: 'Ямайка',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
  {
    id: '446136cb-eea3-4dc8-963a-e25313ae846f',
    name: 'Япон',
    codeName: 'Япон',
    addedAt,
    editedAt: null,
    removedAt: null,
    addedBy: toumkuId,
    editedBy: null,
    removedBy: null,
  },
];
