import { RankTableInsert } from '../schemas';
import {
  ofitserId,
  addedAt,
  userToumkuId,
  ahlagchId,
  gereetAhlagchId,
  gereetId,
  hugatsaatId,
  engiinId,
} from './vars';

export type RankTableSeed = Omit<RankTableInsert, 'id'> & {
  id: string;
};

export const ranksSeed: RankTableSeed[] = [
  {
    id: 'a916c856-31f4-4d91-b14e-747175e5c871',
    rankGroupId: ofitserId,
    name: 'Генерал',
    shortName: 'ген',
    codeName: 'general',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: '226f7ff7-8c9a-4c2c-a485-dff85d6bd67d',
    rankGroupId: ofitserId,
    name: 'Дэслэгч генерал',
    shortName: 'д/ген',
    codeName: 'deslegch-general',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: '61f7a5a0-08ca-4262-9df3-089aa3c0511c',
    rankGroupId: ofitserId,
    name: 'Хошууч генерал',
    shortName: 'х/ген',
    codeName: 'hoshuuch-general',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: '23eaa1be-7ed7-4ea6-b112-6427fb5cbf32',
    rankGroupId: ofitserId,
    name: 'Бригадын генерал',
    shortName: 'б/ген',
    codeName: 'brigade-general',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: '75b50a97-0461-4a60-b096-c25e9f407abd',
    rankGroupId: ofitserId,
    name: 'Хурандаа',
    shortName: 'х/а',
    codeName: 'hurandaa',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: '62b89b34-da72-4b4d-b5d6-0e9c31e7591f',
    rankGroupId: ofitserId,
    name: 'Дэд хурандаа',
    shortName: 'д/х',
    codeName: 'ded-hurandaa',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: '93503157-26c1-4119-a7cb-6f662647d483',
    rankGroupId: ofitserId,
    name: 'Хошууч',
    shortName: 'х/ч',
    codeName: 'hoshuuch',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: 'aca352ea-2e2c-4082-b04d-c238641e5258',
    rankGroupId: ofitserId,
    name: 'Ахмад',
    shortName: 'а/х',
    codeName: 'ahmad',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: '32b2b605-f34b-4602-ace1-2bd068c034c4',
    rankGroupId: ofitserId,
    name: 'Ахлах дэслэгч',
    shortName: 'а/д',
    codeName: 'ahlah-deslegch',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: 'eeb0cfd9-0df1-4c62-8c89-7a6b735c4ee6',
    rankGroupId: ofitserId,
    name: 'Дэслэгч',
    shortName: 'д/ч',
    codeName: 'deslegch',
    addedAt,
    addedBy: userToumkuId,
  },

  {
    id: 'f110173f-a2e4-4ad2-8925-8673f9041c7a',
    rankGroupId: ahlagchId,
    name: 'Тэргүүн ахлагч',
    shortName: 'т/а',
    codeName: 'terguun-ahlagch',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: '6aeb4d05-f0be-4111-a4fb-1b1ee807009f',
    rankGroupId: ahlagchId,
    name: 'Сургагч ахлагч',
    shortName: 'с/а',
    codeName: 'surgagch-ahlagch',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: '3c110827-97fb-4fe4-820f-56d6898a9396',
    rankGroupId: ahlagchId,
    name: 'Ахлах ахлагч',
    shortName: 'с/а',
    codeName: 'ahlah-ahlagch',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: '304be1d4-79c6-42ab-953c-92b29ee3c888',
    rankGroupId: ahlagchId,
    name: 'Ахлагч',
    shortName: 'а/ч',
    codeName: 'ahlagch',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: '360d1312-fa9a-4456-ac87-7d75d07fb400',
    rankGroupId: ahlagchId,
    name: 'Дэд ахлагч',
    shortName: 'д/а',
    codeName: 'ded-ahlagch',
    addedAt,
    addedBy: userToumkuId,
  },

  {
    id: 'aa6b454d-e4ac-42fe-85fd-f945efc8635e',
    rankGroupId: gereetAhlagchId,
    name: 'Тэргүүн ахлагч',
    shortName: 'т/а',
    codeName: 'gereet-terguun-ahlagch',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: '24c78a03-1972-4c20-aec6-a8a78e306462',
    rankGroupId: ahlagchId,
    name: 'Сургагч ахлагч',
    shortName: 'с/а',
    codeName: 'gereet-surgagch-ahlagch',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: '23ec58ce-bb35-4cf7-97ab-9a676ad1b543',
    rankGroupId: ahlagchId,
    name: 'Ахлах ахлагч',
    shortName: 'с/а',
    codeName: 'gereet-ahlah-ahlagch',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: '43c5c2c7-f47d-4287-9d25-1d5d02815cd1',
    rankGroupId: ahlagchId,
    name: 'Ахлагч',
    shortName: 'а/ч',
    codeName: 'gereet-ahlagch',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: '5b02a139-d1b4-458f-bb8d-bb219ddc22fc',
    rankGroupId: ahlagchId,
    name: 'Дэд ахлагч',
    shortName: 'д/а',
    codeName: 'gereet-ded-ahlagch',
    addedAt,
    addedBy: userToumkuId,
  },

  {
    id: 'bdbf98ad-a558-4ffa-9412-3dd7b1add925',
    rankGroupId: gereetId,
    name: 'Ахлах түрүүч',
    shortName: 'а/т',
    codeName: 'gereet-ahlah-turuuch',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: 'bad10ee7-0c8f-4b38-8e14-972aa11e02d0',
    rankGroupId: gereetId,
    name: 'Түрүүч',
    shortName: 'т/ч',
    codeName: 'gereet-turuuch',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: '8ce83d2e-1085-41b6-ba02-d87ece7bb701',
    rankGroupId: gereetId,
    name: 'Дэд түрүүч',
    shortName: 'д/т',
    codeName: 'gereet-ded-turuuch',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: '06a8743a-30f0-4f84-83cc-3d4d8b8b9042',
    rankGroupId: gereetId,
    name: 'Ахлах байлдагч',
    shortName: 'а/б',
    codeName: 'gereet-ahlah-baildagch',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: 'ed83f2cd-2a19-4fc1-8447-bd7050fe8876',
    rankGroupId: gereetId,
    name: 'Байлдагч',
    shortName: 'б/ч',
    codeName: 'gereet-baildagch',
    addedAt,
    addedBy: userToumkuId,
  },

  {
    id: 'ade6c277-a825-430c-9506-21e055241b20',
    rankGroupId: hugatsaatId,
    name: 'Ахлах түрүүч',
    shortName: 'а/т',
    codeName: 'ahlah-turuuch',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: '007e31c8-c419-4141-beea-7a343a1b4a77',
    rankGroupId: hugatsaatId,
    name: 'Түрүүч',
    shortName: 'т/ч',
    codeName: 'turuuch',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: 'a2a32e92-c90a-44f6-8dc9-d485a759b01b',
    rankGroupId: hugatsaatId,
    name: 'Дэд түрүүч',
    shortName: 'д/т',
    codeName: 'ded-turuuch',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: '50ffa4f5-8029-4f95-b627-04bd47a546e1',
    rankGroupId: hugatsaatId,
    name: 'Ахлах байлдагч',
    shortName: 'а/б',
    codeName: 'ahlah-baildagch',
    addedAt,
    addedBy: userToumkuId,
  },
  {
    id: 'c10bc854-b08e-4b94-8d50-b0e4d4513950',
    rankGroupId: hugatsaatId,
    name: 'Байлдагч',
    shortName: 'б/ч',
    codeName: 'baildagch',
    addedAt,
    addedBy: userToumkuId,
  },

  {
    id: '6e7c5a47-55a7-4b3b-860e-cd74f0c036bc',
    rankGroupId: engiinId,
    name: 'Энгийн',
    shortName: 'энгийн',
    codeName: 'engiin',
    addedAt,
    addedBy: userToumkuId,
  },
];
